"""add enum

Revision ID: 1c49d65f748a
Revises: 50cf7ad95fc8
Create Date: 2023-08-18 14:27:09.187709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c49d65f748a'
down_revision = '50cf7ad95fc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements_table', 'side')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements_table', sa.Column('side', sa.String(), nullable=False))
    # ### end Alembic commands ###
