"""change Measurement.data to array[float]

Revision ID: 9363a9456faa
Revises: 0e05eb7f751b
Create Date: 2023-08-22 16:40:08.749163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import ARRAY, Float, String

# revision identifiers, used by Alembic.
revision = '9363a9456faa'
down_revision = '0e05eb7f751b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='measurements_table', column_name='data')
    op.add_column(table_name='measurements_table', column=sa.Column(name='data', type_=ARRAY(Float)))
    # op.drop_index('ix_measurements_table_data', table_name='measurements_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='measurements_table', column_name='data')
    op.add_column(table_name='measurements_table', column=sa.Column(name='data', type_=String(length=320)))
    # op.create_index('ix_measurements_table_data', 'measurements_table', ['data'], unique=False)
    # ### end Alembic commands ###
