"""change measured part literal

Revision ID: 0e05eb7f751b
Revises: 8cbdbad91a70
Create Date: 2023-08-21 16:12:26.121199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e05eb7f751b'
down_revision = '8cbdbad91a70'
branch_labels = None
depends_on = None

meas_enum = sa.Enum('first20', 'second20', 'third20', name='measuredpart_enum', create_constraint=True)
meas_enum_dow = sa.Enum('first10', 'second10', 'third10', name='measuredpart_enum', create_constraint=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements_table', 'measuredpart')
    meas_enum_dow.drop(op.get_bind())
    meas_enum.create(op.get_bind())
    op.add_column('measurements_table', sa.Column('measuredpart', meas_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements_table', 'measuredpart')
    meas_enum.drop(op.get_bind())

    meas_enum_dow.create(op.get_bind())
    op.add_column('measurements_table', sa.Column('measuredpart', meas_enum_dow, nullable=False))


    # ### end Alembic commands ###