"""add timezone=True

Revision ID: 380aacbdc81e
Revises: 909cf240e6db
Create Date: 2023-07-10 19:33:54.541506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380aacbdc81e'
down_revision = '909cf240e6db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
