"""add run_table

Revision ID: 50cf7ad95fc8
Revises: a0097e7050d0
Create Date: 2023-08-18 14:20:33.627707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cf7ad95fc8'
down_revision = 'a0097e7050d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements_table', 'side')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements_table', sa.Column('side', sa.String(), nullable=False))
    # ### end Alembic commands ###
