"""add enum2

Revision ID: 8cbdbad91a70
Revises: 1c49d65f748a
Create Date: 2023-08-18 15:38:53.593071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbdbad91a70'
down_revision = '1c49d65f748a'
branch_labels = None
depends_on = None

meas_enum = sa.Enum('first10', 'second10', 'third10', name='measuredpart_enum', create_constraint=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meas_enum.create(op.get_bind())
    op.add_column('measurements_table', sa.Column('measuredpart', meas_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meas_enum.drop(op.get_bind())
    op.drop_column('measurements_table', 'measuredpart')
    # ### end Alembic commands ###
