"""add run_table

Revision ID: a0097e7050d0
Revises: 99d16655bcd7
Create Date: 2023-08-14 14:55:52.548973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0097e7050d0'
down_revision = '99d16655bcd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('measurements_table', sa.Column('side', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements_table', 'side')
    op.drop_table('run_table')
    # ### end Alembic commands ###
